#crab status -d crab_full_run2_version2_DY_v1/
#crab status -d crab_full_run2_version2_DY_v2/
#crab status -d crab_full_run2_LNuAJJ_EWK_test94X/
#crab status -d crab_full_run2_ST_s/
#crab status -d crab_full_run2_ST_tW_antitop/
#crab status -d crab_full_run2_ST_tW_top/
#crab status -d crab_full_run2_ST_t_2/
#crab status -d crab_full_run2_ST_tbar_2/
#crab status -d crab_full_run2_TTGJets_v1/
#crab status -d crab_full_run2_WGToLNuG/
#crab status -d crab_full_run2_version2_WJets_v1_2/
#crab status -d crab_full_run2_version2_WJets_v2_2/
#crab status -d crab_full_run2_WW_v1_2/
#crab status -d crab_full_run2_WW_v2_2/
#crab status -d crab_full_run2_WZ_v1_2/
#crab status -d crab_full_run2_WZ_v2_2/
#crab status -d crab_full_run2_ZA/
#crab status -d crab_full_run2_ZZ_v1_2/
#crab status -d crab_full_run2_ZZ_v2_2/
#crab status -d crab_full_run2_version2_smuB_v1/
#crab status -d crab_full_run2_version2_smuB_v2/
#crab status -d crab_full_run2_version2_smuC_v1/
#crab status -d crab_full_run2_version2_smuD_v1/
#crab status -d crab_full_run2_version2_smuE_v1/
#crab status -d crab_full_run2_version2_smuF_v1/
#crab status -d crab_full_run2_version2_smuG_v1/
#crab status -d crab_full_run2_version2_smuH_v1/i
crab status -d crab_full_run2_seleB_v1/
crab status -d crab_full_run2_seleB_v2/
crab status -d crab_full_run2_seleC_v1/
crab status -d crab_full_run2_seleD_v1/
crab status -d crab_full_run2_seleE_v1/
crab status -d crab_full_run2_seleF_v1/
crab status -d crab_full_run2_seleG_v1/
crab status -d crab_full_run2_seleH_v1/
