# MC
crab submit -c ./CrabJobsSrc/MC/crab3_analysisDY_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisDY_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisLNuAJJ_EWK_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisLNuAJJ_EWK_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisST_s.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisST_t.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisST_tW_antitop.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisST_tW_top.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisST_tbar.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisTTGJets_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisTTGJets_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisTT_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisTT_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWGToLNuG.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWGToLNuG_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWJets_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWJets_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWW_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWW_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWZ_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisWZ_v2.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisZA.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisZZ_v1.py
crab submit -c ./CrabJobsSrc/MC/crab3_analysisZZ_v2.py
# muon
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuB_v1.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuB_v2.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuC_v1.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuD_v1.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuE_v1.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuF_v1.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuG_v1.py
#crab submit -c ./CrabJobsSrc/SingleMu/crab3_analysis_smuH_v1.py
# electron
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleB_v1.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleB_v2.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleC_v1.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleD_v1.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleE_v1.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleF_v1.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleG_v1.py
#crab submit -c ./CrabJobsSrc/SingleEle/crab3_analysis_seleH_v1.py
